### ISSUE TITLE
Report Firefox addon as e10s compatible

### ISSUE THREAD

**Issue by gerdneuman** [nishanthvijayan/HackerNews-Feed#5]
Your addon works perfect on e10s. I've just it myself for several months on Developer Edition. You should update the manifest to report the addon as compatible so that it does not block the e10s rollout:
- https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/
- https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible

Thanks <3

**Comment by nishanthvijayan** [comment]
I've marked it as multiprocess compatible.
Thank you for your contribution :+1:
